# Generated by Django 5.2 on 2025-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
